-- Phase 3 schema v1. Exact decimals are TEXT, never REAL/NUMERIC.
CREATE TABLE schema_version (
    version INTEGER PRIMARY KEY CHECK(version = 1),
    schema_sha256 TEXT NOT NULL
) STRICT;
CREATE TABLE dataset_source (
    source_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    domain TEXT NOT NULL CHECK(domain IN ('accounting','sales'))
) STRICT;
CREATE TABLE processing_run (
    run_id TEXT PRIMARY KEY,
    schema_version INTEGER NOT NULL REFERENCES schema_version(version),
    ingested_at TEXT NOT NULL,
    manifest_sha256 TEXT NOT NULL,
    validation_sha256 TEXT NOT NULL,
    flags_sha256 TEXT NOT NULL,
    manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)),
    validation_json TEXT NOT NULL CHECK(json_valid(validation_json)),
    approval_json TEXT NOT NULL CHECK(json_valid(approval_json))
) STRICT;
CREATE TABLE run_dataset (
    run_id TEXT NOT NULL REFERENCES processing_run(run_id),
    source_id TEXT NOT NULL REFERENCES dataset_source(source_id),
    source_file TEXT NOT NULL,
    source_sha256 TEXT NOT NULL CHECK(length(source_sha256)=64),
    processed_file TEXT NOT NULL,
    processed_sha256 TEXT NOT NULL CHECK(length(processed_sha256)=64),
    expected_rows INTEGER NOT NULL CHECK(expected_rows>0),
    output_schema_json TEXT NOT NULL CHECK(json_valid(output_schema_json)),
    PRIMARY KEY(run_id,source_id)
) STRICT;
CREATE TABLE source_record (
    record_id TEXT PRIMARY KEY CHECK(length(record_id)=64),
    run_id TEXT NOT NULL,
    source_id TEXT NOT NULL,
    source_row_number INTEGER NOT NULL CHECK(source_row_number>0),
    processed_row_number INTEGER NOT NULL CHECK(processed_row_number>0),
    UNIQUE(run_id,source_id,source_row_number),
    UNIQUE(run_id,source_id,processed_row_number),
    UNIQUE(record_id,run_id,source_id),
    FOREIGN KEY(run_id,source_id) REFERENCES run_dataset(run_id,source_id)
) STRICT;
CREATE TABLE receiver_general_accounting_record (
    record_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    source_id TEXT NOT NULL CHECK(source_id='receiver_general'),
    accounting_control_number TEXT,
    accounting_control_number_raw TEXT NOT NULL,
    accounting_control_number_status TEXT NOT NULL CHECK(accounting_control_number_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    journal_voucher_type_code TEXT,
    journal_voucher_type_code_raw TEXT NOT NULL,
    journal_voucher_type_code_status TEXT NOT NULL CHECK(journal_voucher_type_code_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    fiscal_year TEXT,
    fiscal_year_raw TEXT NOT NULL,
    fiscal_year_status TEXT NOT NULL CHECK(fiscal_year_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    journal_voucher_identifier TEXT,
    journal_voucher_identifier_raw TEXT NOT NULL,
    journal_voucher_identifier_status TEXT NOT NULL CHECK(journal_voucher_identifier_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    accounting_effective_date TEXT CHECK(length(accounting_effective_date)=10 AND accounting_effective_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
    accounting_effective_date_raw TEXT NOT NULL,
    accounting_effective_date_status TEXT NOT NULL CHECK(accounting_effective_date_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    department_number TEXT,
    department_number_raw TEXT NOT NULL,
    department_number_status TEXT NOT NULL CHECK(department_number_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    fiscal_month INTEGER CHECK(fiscal_month BETWEEN 1 AND 12),
    fiscal_month_raw TEXT NOT NULL,
    fiscal_month_status TEXT NOT NULL CHECK(fiscal_month_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    journal_voucher_item_identifier TEXT,
    journal_voucher_item_identifier_raw TEXT NOT NULL,
    journal_voucher_item_identifier_status TEXT NOT NULL CHECK(journal_voucher_item_identifier_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    financial_coding_block TEXT,
    financial_coding_block_raw TEXT NOT NULL,
    financial_coding_block_status TEXT NOT NULL CHECK(financial_coding_block_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    subledger_account_identifier TEXT,
    subledger_account_identifier_raw TEXT NOT NULL,
    subledger_account_identifier_status TEXT NOT NULL CHECK(subledger_account_identifier_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    credit_debit_code TEXT,
    credit_debit_code_raw TEXT NOT NULL,
    credit_debit_code_status TEXT NOT NULL CHECK(credit_debit_code_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    journal_voucher_item_amount TEXT CHECK(journal_voucher_item_amount IS NULL OR (length(journal_voucher_item_amount)-length(replace(journal_voucher_item_amount,'.',''))=1 AND length(journal_voucher_item_amount)-length(replace(journal_voucher_item_amount,'-',''))<=1 AND instr(journal_voucher_item_amount,'-') IN (0,1) AND ltrim(journal_voucher_item_amount,'-') NOT GLOB '*[^0-9.]*' AND instr(ltrim(journal_voucher_item_amount,'-'),'.')>1 AND substr(journal_voucher_item_amount,-1) GLOB '[0-9]')),
    journal_voucher_item_amount_raw TEXT NOT NULL,
    journal_voucher_item_amount_status TEXT NOT NULL CHECK(journal_voucher_item_amount_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    control_data_type TEXT,
    control_data_type_raw TEXT NOT NULL,
    control_data_type_status TEXT NOT NULL CHECK(control_data_type_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    accounting_summary_transaction_line_count INTEGER CHECK(accounting_summary_transaction_line_count>=0),
    accounting_summary_transaction_line_count_raw TEXT NOT NULL,
    accounting_summary_transaction_line_count_status TEXT NOT NULL CHECK(accounting_summary_transaction_line_count_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    gbs_control_number TEXT,
    gbs_control_number_raw TEXT NOT NULL,
    gbs_control_number_status TEXT NOT NULL CHECK(gbs_control_number_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    general_ledger_account_code TEXT,
    general_ledger_account_code_raw TEXT NOT NULL,
    general_ledger_account_code_status TEXT NOT NULL CHECK(general_ledger_account_code_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    original_currency TEXT,
    currency_code TEXT,
    currency_source TEXT,
    currency_status TEXT NOT NULL CHECK(currency_status IN ('UNKNOWN','INFERRED','CONFIRMED')),
    CHECK ((accounting_control_number IS NULL AND accounting_control_number_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (accounting_control_number IS NOT NULL AND accounting_control_number_status IN ('kept','parsed','standardized'))),
    CHECK (accounting_control_number_status!='source_missing' OR accounting_control_number_raw=''),
    CHECK ((journal_voucher_type_code IS NULL AND journal_voucher_type_code_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (journal_voucher_type_code IS NOT NULL AND journal_voucher_type_code_status IN ('kept','parsed','standardized'))),
    CHECK (journal_voucher_type_code_status!='source_missing' OR journal_voucher_type_code_raw=''),
    CHECK ((fiscal_year IS NULL AND fiscal_year_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (fiscal_year IS NOT NULL AND fiscal_year_status IN ('kept','parsed','standardized'))),
    CHECK (fiscal_year_status!='source_missing' OR fiscal_year_raw=''),
    CHECK ((journal_voucher_identifier IS NULL AND journal_voucher_identifier_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (journal_voucher_identifier IS NOT NULL AND journal_voucher_identifier_status IN ('kept','parsed','standardized'))),
    CHECK (journal_voucher_identifier_status!='source_missing' OR journal_voucher_identifier_raw=''),
    CHECK ((accounting_effective_date IS NULL AND accounting_effective_date_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (accounting_effective_date IS NOT NULL AND accounting_effective_date_status IN ('kept','parsed','standardized'))),
    CHECK (accounting_effective_date_status!='source_missing' OR accounting_effective_date_raw=''),
    CHECK ((department_number IS NULL AND department_number_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (department_number IS NOT NULL AND department_number_status IN ('kept','parsed','standardized'))),
    CHECK (department_number_status!='source_missing' OR department_number_raw=''),
    CHECK ((fiscal_month IS NULL AND fiscal_month_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (fiscal_month IS NOT NULL AND fiscal_month_status IN ('kept','parsed','standardized'))),
    CHECK (fiscal_month_status!='source_missing' OR fiscal_month_raw=''),
    CHECK ((journal_voucher_item_identifier IS NULL AND journal_voucher_item_identifier_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (journal_voucher_item_identifier IS NOT NULL AND journal_voucher_item_identifier_status IN ('kept','parsed','standardized'))),
    CHECK (journal_voucher_item_identifier_status!='source_missing' OR journal_voucher_item_identifier_raw=''),
    CHECK ((financial_coding_block IS NULL AND financial_coding_block_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (financial_coding_block IS NOT NULL AND financial_coding_block_status IN ('kept','parsed','standardized'))),
    CHECK (financial_coding_block_status!='source_missing' OR financial_coding_block_raw=''),
    CHECK ((subledger_account_identifier IS NULL AND subledger_account_identifier_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (subledger_account_identifier IS NOT NULL AND subledger_account_identifier_status IN ('kept','parsed','standardized'))),
    CHECK (subledger_account_identifier_status!='source_missing' OR subledger_account_identifier_raw=''),
    CHECK ((credit_debit_code IS NULL AND credit_debit_code_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (credit_debit_code IS NOT NULL AND credit_debit_code_status IN ('kept','parsed','standardized'))),
    CHECK (credit_debit_code_status!='source_missing' OR credit_debit_code_raw=''),
    CHECK ((journal_voucher_item_amount IS NULL AND journal_voucher_item_amount_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (journal_voucher_item_amount IS NOT NULL AND journal_voucher_item_amount_status IN ('kept','parsed','standardized'))),
    CHECK (journal_voucher_item_amount_status!='source_missing' OR journal_voucher_item_amount_raw=''),
    CHECK ((control_data_type IS NULL AND control_data_type_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (control_data_type IS NOT NULL AND control_data_type_status IN ('kept','parsed','standardized'))),
    CHECK (control_data_type_status!='source_missing' OR control_data_type_raw=''),
    CHECK ((accounting_summary_transaction_line_count IS NULL AND accounting_summary_transaction_line_count_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (accounting_summary_transaction_line_count IS NOT NULL AND accounting_summary_transaction_line_count_status IN ('kept','parsed','standardized'))),
    CHECK (accounting_summary_transaction_line_count_status!='source_missing' OR accounting_summary_transaction_line_count_raw=''),
    CHECK ((gbs_control_number IS NULL AND gbs_control_number_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (gbs_control_number IS NOT NULL AND gbs_control_number_status IN ('kept','parsed','standardized'))),
    CHECK (gbs_control_number_status!='source_missing' OR gbs_control_number_raw=''),
    CHECK ((general_ledger_account_code IS NULL AND general_ledger_account_code_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (general_ledger_account_code IS NOT NULL AND general_ledger_account_code_status IN ('kept','parsed','standardized'))),
    CHECK (general_ledger_account_code_status!='source_missing' OR general_ledger_account_code_raw=''),
    CHECK(currency_status!='UNKNOWN' OR (currency_code IS NULL AND original_currency IS NULL AND currency_source IS NULL)),
    CHECK(currency_status='UNKNOWN' OR (currency_code IS NOT NULL AND currency_source IS NOT NULL)),
    CHECK(currency_code IS NULL OR (length(currency_code)=3 AND currency_code NOT GLOB '*[^A-Z]*')),
    FOREIGN KEY(record_id,run_id,source_id) REFERENCES source_record(record_id,run_id,source_id)
) STRICT;
CREATE TABLE company_financial_sales_record (
    record_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    source_id TEXT NOT NULL CHECK(source_id='company_financials'),
    segment TEXT,
    segment_raw TEXT NOT NULL,
    segment_status TEXT NOT NULL CHECK(segment_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    country TEXT,
    country_raw TEXT NOT NULL,
    country_status TEXT NOT NULL CHECK(country_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    product TEXT,
    product_raw TEXT NOT NULL,
    product_status TEXT NOT NULL CHECK(product_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    discount_band TEXT,
    discount_band_raw TEXT NOT NULL,
    discount_band_status TEXT NOT NULL CHECK(discount_band_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    units_sold TEXT CHECK(units_sold IS NULL OR (length(units_sold)-length(replace(units_sold,'.',''))=1 AND length(units_sold)-length(replace(units_sold,'-',''))<=1 AND instr(units_sold,'-') IN (0,1) AND ltrim(units_sold,'-') NOT GLOB '*[^0-9.]*' AND instr(ltrim(units_sold,'-'),'.')>1 AND substr(units_sold,-1) GLOB '[0-9]')),
    units_sold_raw TEXT NOT NULL,
    units_sold_status TEXT NOT NULL CHECK(units_sold_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    manufacturing_price TEXT CHECK(manufacturing_price IS NULL OR (length(manufacturing_price)-length(replace(manufacturing_price,'.',''))=1 AND length(manufacturing_price)-length(replace(manufacturing_price,'-',''))<=1 AND instr(manufacturing_price,'-') IN (0,1) AND ltrim(manufacturing_price,'-') NOT GLOB '*[^0-9.]*' AND instr(ltrim(manufacturing_price,'-'),'.')>1 AND substr(manufacturing_price,-1) GLOB '[0-9]')),
    manufacturing_price_raw TEXT NOT NULL,
    manufacturing_price_status TEXT NOT NULL CHECK(manufacturing_price_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    sale_price TEXT CHECK(sale_price IS NULL OR (length(sale_price)-length(replace(sale_price,'.',''))=1 AND length(sale_price)-length(replace(sale_price,'-',''))<=1 AND instr(sale_price,'-') IN (0,1) AND ltrim(sale_price,'-') NOT GLOB '*[^0-9.]*' AND instr(ltrim(sale_price,'-'),'.')>1 AND substr(sale_price,-1) GLOB '[0-9]')),
    sale_price_raw TEXT NOT NULL,
    sale_price_status TEXT NOT NULL CHECK(sale_price_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    gross_sales TEXT CHECK(gross_sales IS NULL OR (length(gross_sales)-length(replace(gross_sales,'.',''))=1 AND length(gross_sales)-length(replace(gross_sales,'-',''))<=1 AND instr(gross_sales,'-') IN (0,1) AND ltrim(gross_sales,'-') NOT GLOB '*[^0-9.]*' AND instr(ltrim(gross_sales,'-'),'.')>1 AND substr(gross_sales,-1) GLOB '[0-9]')),
    gross_sales_raw TEXT NOT NULL,
    gross_sales_status TEXT NOT NULL CHECK(gross_sales_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    discounts TEXT CHECK(discounts IS NULL OR (length(discounts)-length(replace(discounts,'.',''))=1 AND length(discounts)-length(replace(discounts,'-',''))<=1 AND instr(discounts,'-') IN (0,1) AND ltrim(discounts,'-') NOT GLOB '*[^0-9.]*' AND instr(ltrim(discounts,'-'),'.')>1 AND substr(discounts,-1) GLOB '[0-9]')),
    discounts_raw TEXT NOT NULL,
    discounts_status TEXT NOT NULL CHECK(discounts_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    sales TEXT CHECK(sales IS NULL OR (length(sales)-length(replace(sales,'.',''))=1 AND length(sales)-length(replace(sales,'-',''))<=1 AND instr(sales,'-') IN (0,1) AND ltrim(sales,'-') NOT GLOB '*[^0-9.]*' AND instr(ltrim(sales,'-'),'.')>1 AND substr(sales,-1) GLOB '[0-9]')),
    sales_raw TEXT NOT NULL,
    sales_status TEXT NOT NULL CHECK(sales_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    cogs TEXT CHECK(cogs IS NULL OR (length(cogs)-length(replace(cogs,'.',''))=1 AND length(cogs)-length(replace(cogs,'-',''))<=1 AND instr(cogs,'-') IN (0,1) AND ltrim(cogs,'-') NOT GLOB '*[^0-9.]*' AND instr(ltrim(cogs,'-'),'.')>1 AND substr(cogs,-1) GLOB '[0-9]')),
    cogs_raw TEXT NOT NULL,
    cogs_status TEXT NOT NULL CHECK(cogs_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    profit TEXT CHECK(profit IS NULL OR (length(profit)-length(replace(profit,'.',''))=1 AND length(profit)-length(replace(profit,'-',''))<=1 AND instr(profit,'-') IN (0,1) AND ltrim(profit,'-') NOT GLOB '*[^0-9.]*' AND instr(ltrim(profit,'-'),'.')>1 AND substr(profit,-1) GLOB '[0-9]')),
    profit_raw TEXT NOT NULL,
    profit_status TEXT NOT NULL CHECK(profit_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    period_date TEXT CHECK(length(period_date)=10 AND period_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
    period_date_raw TEXT NOT NULL,
    period_date_status TEXT NOT NULL CHECK(period_date_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    month_number INTEGER CHECK(month_number BETWEEN 1 AND 12),
    month_number_raw TEXT NOT NULL,
    month_number_status TEXT NOT NULL CHECK(month_number_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    month_name TEXT,
    month_name_raw TEXT NOT NULL,
    month_name_status TEXT NOT NULL CHECK(month_name_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    year INTEGER,
    year_raw TEXT NOT NULL,
    year_status TEXT NOT NULL CHECK(year_status IN ('kept','parsed','standardized','source_missing','unresolved_placeholder','parsing_failed')),
    original_currency TEXT,
    currency_code TEXT,
    currency_source TEXT,
    currency_status TEXT NOT NULL CHECK(currency_status IN ('UNKNOWN','INFERRED','CONFIRMED')),
    CHECK ((segment IS NULL AND segment_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (segment IS NOT NULL AND segment_status IN ('kept','parsed','standardized'))),
    CHECK (segment_status!='source_missing' OR segment_raw=''),
    CHECK ((country IS NULL AND country_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (country IS NOT NULL AND country_status IN ('kept','parsed','standardized'))),
    CHECK (country_status!='source_missing' OR country_raw=''),
    CHECK ((product IS NULL AND product_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (product IS NOT NULL AND product_status IN ('kept','parsed','standardized'))),
    CHECK (product_status!='source_missing' OR product_raw=''),
    CHECK ((discount_band IS NULL AND discount_band_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (discount_band IS NOT NULL AND discount_band_status IN ('kept','parsed','standardized'))),
    CHECK (discount_band_status!='source_missing' OR discount_band_raw=''),
    CHECK ((units_sold IS NULL AND units_sold_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (units_sold IS NOT NULL AND units_sold_status IN ('kept','parsed','standardized'))),
    CHECK (units_sold_status!='source_missing' OR units_sold_raw=''),
    CHECK ((manufacturing_price IS NULL AND manufacturing_price_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (manufacturing_price IS NOT NULL AND manufacturing_price_status IN ('kept','parsed','standardized'))),
    CHECK (manufacturing_price_status!='source_missing' OR manufacturing_price_raw=''),
    CHECK ((sale_price IS NULL AND sale_price_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (sale_price IS NOT NULL AND sale_price_status IN ('kept','parsed','standardized'))),
    CHECK (sale_price_status!='source_missing' OR sale_price_raw=''),
    CHECK ((gross_sales IS NULL AND gross_sales_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (gross_sales IS NOT NULL AND gross_sales_status IN ('kept','parsed','standardized'))),
    CHECK (gross_sales_status!='source_missing' OR gross_sales_raw=''),
    CHECK ((discounts IS NULL AND discounts_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (discounts IS NOT NULL AND discounts_status IN ('kept','parsed','standardized'))),
    CHECK (discounts_status!='source_missing' OR discounts_raw=''),
    CHECK ((sales IS NULL AND sales_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (sales IS NOT NULL AND sales_status IN ('kept','parsed','standardized'))),
    CHECK (sales_status!='source_missing' OR sales_raw=''),
    CHECK ((cogs IS NULL AND cogs_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (cogs IS NOT NULL AND cogs_status IN ('kept','parsed','standardized'))),
    CHECK (cogs_status!='source_missing' OR cogs_raw=''),
    CHECK ((profit IS NULL AND profit_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (profit IS NOT NULL AND profit_status IN ('kept','parsed','standardized'))),
    CHECK (profit_status!='source_missing' OR profit_raw=''),
    CHECK ((period_date IS NULL AND period_date_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (period_date IS NOT NULL AND period_date_status IN ('kept','parsed','standardized'))),
    CHECK (period_date_status!='source_missing' OR period_date_raw=''),
    CHECK ((month_number IS NULL AND month_number_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (month_number IS NOT NULL AND month_number_status IN ('kept','parsed','standardized'))),
    CHECK (month_number_status!='source_missing' OR month_number_raw=''),
    CHECK ((month_name IS NULL AND month_name_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (month_name IS NOT NULL AND month_name_status IN ('kept','parsed','standardized'))),
    CHECK (month_name_status!='source_missing' OR month_name_raw=''),
    CHECK ((year IS NULL AND year_status IN ('source_missing','unresolved_placeholder','parsing_failed')) OR (year IS NOT NULL AND year_status IN ('kept','parsed','standardized'))),
    CHECK (year_status!='source_missing' OR year_raw=''),
    CHECK(currency_status!='UNKNOWN' OR (currency_code IS NULL AND original_currency IS NULL AND currency_source IS NULL)),
    CHECK(currency_status='UNKNOWN' OR (currency_code IS NOT NULL AND currency_source IS NOT NULL)),
    CHECK(currency_code IS NULL OR (length(currency_code)=3 AND currency_code NOT GLOB '*[^A-Z]*')),
    FOREIGN KEY(record_id,run_id,source_id) REFERENCES source_record(record_id,run_id,source_id)
) STRICT;
CREATE TABLE data_quality_flag (
    flag_id INTEGER PRIMARY KEY,
    run_id TEXT NOT NULL,
    source_id TEXT NOT NULL,
    record_id TEXT,
    flag_row_number INTEGER NOT NULL CHECK(flag_row_number>0),
    scope TEXT NOT NULL CHECK(scope IN ('dataset','field','record_check','record')),
    source_file TEXT NOT NULL,
    source_sha256 TEXT NOT NULL,
    source_row_number TEXT NOT NULL,
    field TEXT NOT NULL,
    rule_id TEXT NOT NULL,
    flag TEXT NOT NULL,
    status TEXT NOT NULL,
    raw_value TEXT NOT NULL,
    reason TEXT NOT NULL,
    UNIQUE(run_id,flag_row_number),
    CHECK((scope='dataset' AND record_id IS NULL AND source_row_number='') OR
          (scope!='dataset' AND record_id IS NOT NULL AND source_row_number!='')),
    FOREIGN KEY(run_id,source_id) REFERENCES run_dataset(run_id,source_id),
    FOREIGN KEY(record_id,run_id,source_id) REFERENCES source_record(record_id,run_id,source_id)
) STRICT;
CREATE INDEX rg_effective_date ON receiver_general_accounting_record(accounting_effective_date);
CREATE INDEX rg_department_voucher ON receiver_general_accounting_record(department_number,journal_voucher_type_code);
CREATE INDEX rg_direction ON receiver_general_accounting_record(credit_debit_code);
CREATE INDEX rg_ledger ON receiver_general_accounting_record(general_ledger_account_code) WHERE general_ledger_account_code IS NOT NULL;
CREATE INDEX sales_period ON company_financial_sales_record(period_date);
CREATE INDEX sales_categories ON company_financial_sales_record(country,segment,product,discount_band);
CREATE INDEX quality_record ON data_quality_flag(record_id) WHERE record_id IS NOT NULL;
CREATE INDEX quality_condition ON data_quality_flag(run_id,source_id,flag);
